#!/bin/sh /etc/rc.common

START=99
STOP=11

USE_PROCD=1
PROG=/usr/bin/AdhocServer

start_service() {
	procd_open_instance
	procd_set_param respawn
	procd_set_param stderr 1
	procd_set_param stdout 1

	procd_set_param command "${PROG}"
	procd_set_param user nobody
        procd_set_param pidfile "/var/run/AdhocServer.pid"

	procd_close_instance
}

stop_service() {
	service_stop ${PROG}
}
